version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.3
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    volumes:
      - ./mlruns:/mlflow
    restart: unless-stopped
